### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by webxoss** [Deardrops/webxoss-deckeditor2#2]
## js

See eslint config.

## css

* `css-next` only
* One space behind `:`, `,`
* Indent by 2 spaces
* `;` required
* Color: `#aabbcc`, lower case
* No id selector
* No `!important`

## vue

Single file component with `script`, `template` and `style` *in order*.

Template:

```html
<div
  class="class"
  :data="data"
  @event="handler">
  <span>{{ text }}</span>
</div>
```

Style:

* ALWAYS use `scoped` or `module` on component style

**Comment by Deardrops** [comment]
window平台上,git迁出时会自动把换行符LF转换成CRLF。
而eslint的设置中把js文件中CRLF标记为错误。
需要设置
`git config --global core.autocrlf input`
来避免这个问题。
可否修改eslint中相关配置？

**Comment by webxoss** [comment]
统一用LF
