### ISSUE TITLE
Features 可选特性

### ISSUE THREAD

**Issue by Deardrops** [Deardrops/webxoss-deckeditor2#49]
- [x] #51 Preview视图使用 **未裁剪** 的卡片

- [x] #56 切换视图的Icon放在一个更合适的位置

- [x] #51 Preview视图 ~~同时显示主卡组的分身卡组的数量~~ 不显示卡组数量

- [ ] Preview视图的卡片 **圆角 + 阴影**

**Comment by webxoss** [comment]
最后一个不做了吧，感觉会丑
